Add a README.md file
Teradata/mule-teradata-connector pull request #7
Opened 2022-09-14 19:50 UTC by tannguyen16

Add a README.md file

2022-09-15 01:26 UTC, adamtwo requested changes

2022-09-15 01:26 UTC, adamtwo commented on README.md
> +Anypoint Connector for Teradata (Teradata Connector) establishes communication between your Mule app and a Teradata relational database, enabling you to connect with your Teradata Vantage instance to
```suggestion
Anypoint Connector for Teradata (Teradata Connector) establishes communication between your Mule app and a Teradata Vantage database, enabling you to connect with your Teradata Vantage instance to load data and run SQL queries in Teradata Vantage tables.
```

2022-09-15 01:26 UTC, adamtwo commented on README.md
> +- Teradata Vantage API
```suggestion
- Teradata Vantage SQL
```

2022-09-15 01:26 UTC, adamtwo commented on README.md
> +- Creating a Mule app using Anypoint Studio (Studio)
The other elements on the list are nouns so I would change this one to a noun as well,e.g. :

```suggestion
- Anypoint Studio (Studio)
```

2022-09-16 17:01 UTC, tannguyen16 commented
Hey Adam, I have updated the README file according to the comments! Please check once you have a chance. Thank you!

2022-09-16 18:21 UTC, adamtwo approved these changes

2022-09-16 19:01 UTC, merged